#!/bin/sh

self="$(realpath "$0")"
GIT_HOOKS_DIR="$(dirname "$self")" ; export GIT_HOOKS
POST_COMMIT_HOOKS_DIR="$GIT_HOOKS_DIR/post-commit.d" ; export POST_COMMIT_HOOKS_DIR
BASE_DIR="$(dirname "$(dirname "$GIT_HOOKS_DIR")")" ; export BASE_DIR

_ifs_save="$IFS"
IFS=$'\n'
for i in $(find "$POST_COMMIT_HOOKS_DIR" -type f -executable); do
    "$i" "$@" || exit $?
done
IFS="$_ifs_save"
