FROM docker.io/library/python:3.12-slim-trixie
ENV DEBUG=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1
ENV PTHON_POETRY=YES
ENV VIRTUAL_ENV=.venv
ENV CONTAINERIZED=1
ENV MEDIA_ROOT=/data/media
ENV STATIC_ROOT=/data/static
ENV VIRTUAL_ENV=/venv

VOLUME /data

RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y --no-install-recommends \
        build-essential \
        gettext-dev \
        libreadline-dev \
        libpq-dev \
        libmariadb-dev \
    && rm -rf /var/lib/apt/lists/* \
    && mkdir -p /app /data/media /data/static /data/local_settings .venv \
    && ln -s /venv /app/.venv \
    && pip install --upgrade pip setuptools wheel \
    && pip install poetry

COPY . /app
WORKDIR /app

RUN poetry config virtualenvs.in-project true \
    && touch /data/local_settings/__init__.py \
    && if [ -d /app/django_project/local_settings ]; then rm -rf /app/django_project/local_settings; fi \
    && ln -s /data/local_settings /app/django_project/local_settings \
    && poetry install --no-interaction --all --no-root \
    && chmod +x /app/run.sh \
    && ln -s /app/run.sh /usr/local/bin/run.sh \
    && ln -s /app/run.sh /usr/local/bin/run


EXPOSE 8000
ENTRYPOINT ["/app/run.sh"]
