FROM docker.io/library/python:3.13-slim-trixie
ENV DEBUG=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1
ENV PTHON_POETRY=YES
ENV VIRTUAL_ENV=.venv
ENV CONTAINERIZED=1
ENV MEDIA_ROOT=/data/media
ENV STATIC_ROOT=/data/static
ENV VIRTUAL_ENV=/venv

VOLUME /data

RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y --no-install-recommends \
        build-essential \
        python3-dev \
        gettext \
        libreadline-dev \
        libpq-dev \
        libmariadb-dev \
        apache2-utils \
        apache2-bin \
        apache2-dev \
        libapache2-mod-wsgi-py3 \
        uwsgi \
        uwsgi-plugin-python3 \
    && sh -c "echo 'daemon off;' >> /etc/apache2/apache2.conf" \
    && a2enmod wsgi ssl \
    && rm -rf /var/lib/apt/lists/* \
    && mkdir -p /venv /app /data/media /data/static /data/.config \
    && ln -s /venv /app/.venv \
    && pip install --upgrade pip setuptools wheel \
    && pip install poetry

COPY . /app
WORKDIR /app

RUN poetry config virtualenvs.in-project true \
    && touch /data/.config/__init__.py \
    && if [ -d /app/django_project/local_settings ]; then rm -rf /app/django_project/local_settings; fi \
    && ln -s /data/.config /app/django_project/local_settings \
    && poetry install --no-interaction --all-groups --no-root \
    && chmod +x /app/run.sh \
    && ln -s /app/run.sh /usr/local/bin/run.sh \
    && ln -s /app/run.sh /usr/local/bin/run \
    && ln -s /app/run.sh /usr/local/bin/entrypoint.sh \
    && ln -s /data/.config/uwsgi.ini /etc/uwsgi/apps-available/uwsgi.ini \
    && ln -s /etc/uwsgi/apps-available/uwsgi.ini /etc/uwsgi/apps-enabled/uwsgi.ini
