"""
Django settings for django_project project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from .env import ENV

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ENV('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!

LOCAL_SETTINGS_DIR = BASE_DIR / "django_project" / "local_settings"
_local_settings_file = LOCAL_SETTINGS_DIR / "settings.py"
if _local_settings_file.exists():
    from .local_settings import settings as local_settings
    DEBUG = getattr(local_settings, "DEBUG", ENV("DEBUG"))
else:
    DEBUG = ENV('DEBUG')

ALLOWED_HOSTS = ENV('ALLOWED_HOSTS')

# Application definition

django_apps = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
)

allauth_apps = (
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
)

third_party_apps = [
    'django_extensions',
    'widget_tweaks',
]

project_apps = []

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'django_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if ENV('DATABASE_CONFIG_METHOD') == 'url':
    DATABASES = {
        'default': ENV.db_url('DATABASE_URL'),
    }
elif ENV('DATABASE_CONFIG_METHOD') in ['postgresql','pgsql', 'postgres', 'psql']:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': ENV('POSTGRES_DB'),
            'USER': ENV('POSTGRES_USER'),
            'PASSWORD': ENV('POSTGRES_PASSWORD'),
            'HOST': ENV('POSTGRES_HOST'),
            'PORT': ENV('POSTGRES_PORT'),
        }
    }
elif ENV('DATABASE_CONFIG_METHOD') in ['mysql', 'mariadb']:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': ENV('MYSQL_DB'),
            'USER': ENV('MYSQL_USER'),
            'PASSWORD': ENV('MYSQL_PASSWORD'),
            'HOST': ENV('MYSQL_HOST'),
            'PORT': ENV('MYSQL_PORT'),
        }
    }
elif ENV('DATABASE_CONFIG_METHOD') == 'sqlite':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': ENV('SQLITE_DB_NAME'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / '.data' / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = ENV('LANGUAGE_CODE', default='en-us')
USE_I18N = ENV('USE_I18N', default=True)

USE_TZ = ENV('USE_TZ', default=True)
TIME_ZONE = ENV('TIME_ZONE', default='UTC')

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SETTINGS_DIR = Path(__file__).resolve().parent
LOCAL_SETTINGS_DIR = SETTINGS_DIR / "local_settings"
if ENV('CONTAINERIZED'):
    if Path('/etc/django-env').exists():
        ENV.read_env('/etc/django-env')

EMAIL_BACKEND = ENV('EMAIL_BACKEND')
EMAIL_HOST = ENV('EMAIL_HOST')
EMAIL_PORT = ENV('EMAIL_PORT')
EMAIL_HOST_USER = ENV('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = ENV('EMAIL_HOST_PASSWORD')
EMAIL_USE_TLS = ENV('EMAIL_USE_TLS')
EMAIL_USE_SSL = ENV('EMAIL_USE_SSL')
DEFAULT_FROM_EMAIL = ENV('DEFAULT_FROM_EMAIL')
EMAIL_SUBJECT_PREFIX = ENV('EMAIL_SUBJECT_PREFIX')

ADMINS = ENV('ADMINS')
ADMIN_EMAIL_BACKEND = ENV('ADMIN_EMAIL_BACKEND')
ADMIN_EMAIL_HOST = ENV('ADMIN_EMAIL_HOST')
ADMIN_EMAIL_PORT = ENV('ADMIN_EMAIL_PORT')
ADMIN_EMAIL_HOST_USER = ENV('ADMIN_EMAIL_HOST_USER')
ADMIN_EMAIL_HOST_PASSWORD = ENV('ADMIN_EMAIL_HOST_PASSWORD')
ADMIN_EMAIL_USE_TLS = ENV('ADMIN_EMAIL_USE_TLS')
ADMIN_EMAIL_USE_SSL = ENV('ADMIN_EMAIL_USE_SSL')
ADMIN_DEFAULT_FROM_EMAIL = ENV('ADMIN_DEFAULT_FROM_EMAIL')
ADMIN_EMAIL_SUBJECT_PREFIX = ENV('ADMIN_EMAIL_SUBJECT_PREFIX')

MANAGERS = ENV('MANAGERS')
MANAGER_EMAIL_BACKEND = ENV('MANAGER_EMAIL_BACKEND')
MANAGER_EMAIL_HOST = ENV('MANAGER_EMAIL_HOST')
MANAGER_EMAIL_PORT = ENV('MANAGER_EMAIL_PORT')
MANAGER_EMAIL_HOST_USER = ENV('MANAGER_EMAIL_HOST_USER')
MANAGER_EMAIL_HOST_PASSWORD = ENV('MANAGER_EMAIL_HOST_PASSWORD')
MANAGER_EMAIL_USE_TLS = ENV('MANAGER_EMAIL_USE_TLS')
MANAGER_EMAIL_USE_SSL = ENV('MANAGER_EMAIL_USE_SSL')
MANAGER_DEFAULT_FROM_EMAIL = ENV('MANAGER_DEFAULT_FROM_EMAIL')
MANAGER_EMAIL_SUBJECT_PREFIX = ENV('MANAGER_EMAIL_SUBJECT_PREFIX')


if DEBUG:
    _debug_settings_file = SETTINGS_DIR / "debug_settings.py"
    if _debug_settings_file.exists():
        from .debug_settings import *
    _debug_settings_file = LOCAL_SETTINGS_DIR / "debug_settings.py"
    del _debug_settings_file


    third_party_apps += [
        'debug_toolbar',
        'django_browser_reload',
    ]
    MIDDLEWARE.insert(0, 'debug_toolbar.middleware.DebugToolbarMiddleware')
    MIDDLEWARE.insert(0, 'django_browser_reload.middleware.BrowserReloadMiddleware')

    _debug_env = Path(BASE_DIR) / "django_project" / "local_settings" / "debug_env"
else:
    _production_settings_file = SETTINGS_DIR / "production_settings.py"
    if _production_settings_file.exists():
        from .production_settings import *
    del _production_settings_file

# Load local settings if available, these can override all other settings and are not tracked in version control
if _local_settings_file.exists():
    from .local_settings.settings import * # noqa: F401, F403
del _local_settings_file

if DEBUG:
    _debug_settings_file = LOCAL_SETTINGS_DIR / "debug_settings.py"
    if _debug_settings_file.exists():
        from .local_settings.debug_settings import *
    del _debug_settings_file
else:
    _production_settings_file = LOCAL_SETTINGS_DIR / "production_settings.py"
    if _production_settings_file.exists():
        from .local_settings.production_settings import *
    del _production_settings_file

INSTALLED_APPS = (
    *django_apps,
    *allauth_apps,
    *third_party_apps,
    *project_apps
)
del django_apps, allauth_apps, third_party_apps, project_apps
